Don't assign unused value
Error: CLANG_WARNING:
rsyslog-7.4.10/plugins/omelasticsearch/omelasticsearch.c:208:13: warning: Value stored to 'r' is never read