Use uchar instead of char for type size reference
Error: CLANG_WARNING:
rsyslog-7.4.10/runtime/msg.c:3102:23: warning: Result of 'malloc' is converted to a pointer of type 'uchar', which is incompatible with sizeof operand type 'char'
rsyslog-7.4.10/runtime/debug.h:146:20: note: expanded from macro 'MALLOC'

Error: CLANG_WARNING:
rsyslog-7.4.10/runtime/msg.c:3280:23: warning: Result of 'malloc' is converted to a pointer of type 'uchar', which is incompatible with sizeof operand type 'char'
rsyslog-7.4.10/runtime/debug.h:146:20: note: expanded from macro 'MALLOC'

Error: CLANG_WARNING:
rsyslog-7.4.10/runtime/msg.c:3334:19: warning: Result of 'malloc' is converted to a pointer of type 'uchar', which is incompatible with sizeof operand type 'char'
rsyslog-7.4.10/runtime/debug.h:146:20: note: expanded from macro 'MALLOC'